// Generated by gencpp from file bismillah_fp/koordinat_bola.msg
// DO NOT EDIT!


#ifndef BISMILLAH_FP_MESSAGE_KOORDINAT_BOLA_H
#define BISMILLAH_FP_MESSAGE_KOORDINAT_BOLA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bismillah_fp
{
template <class ContainerAllocator>
struct koordinat_bola_
{
  typedef koordinat_bola_<ContainerAllocator> Type;

  koordinat_bola_()
    : x(0)
    , y(0)  {
    }
  koordinat_bola_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::bismillah_fp::koordinat_bola_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bismillah_fp::koordinat_bola_<ContainerAllocator> const> ConstPtr;

}; // struct koordinat_bola_

typedef ::bismillah_fp::koordinat_bola_<std::allocator<void> > koordinat_bola;

typedef boost::shared_ptr< ::bismillah_fp::koordinat_bola > koordinat_bolaPtr;
typedef boost::shared_ptr< ::bismillah_fp::koordinat_bola const> koordinat_bolaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bismillah_fp::koordinat_bola_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bismillah_fp::koordinat_bola_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bismillah_fp::koordinat_bola_<ContainerAllocator1> & lhs, const ::bismillah_fp::koordinat_bola_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bismillah_fp::koordinat_bola_<ContainerAllocator1> & lhs, const ::bismillah_fp::koordinat_bola_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bismillah_fp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bismillah_fp::koordinat_bola_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bismillah_fp::koordinat_bola_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bismillah_fp::koordinat_bola_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bismillah_fp::koordinat_bola_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bismillah_fp::koordinat_bola_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bismillah_fp::koordinat_bola_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bismillah_fp::koordinat_bola_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b834ede922a0fff22c43585c533b49f";
  }

  static const char* value(const ::bismillah_fp::koordinat_bola_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b834ede922a0fffULL;
  static const uint64_t static_value2 = 0x22c43585c533b49fULL;
};

template<class ContainerAllocator>
struct DataType< ::bismillah_fp::koordinat_bola_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bismillah_fp/koordinat_bola";
  }

  static const char* value(const ::bismillah_fp::koordinat_bola_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bismillah_fp::koordinat_bola_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n"
"int64 y\n"
;
  }

  static const char* value(const ::bismillah_fp::koordinat_bola_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bismillah_fp::koordinat_bola_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct koordinat_bola_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bismillah_fp::koordinat_bola_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bismillah_fp::koordinat_bola_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BISMILLAH_FP_MESSAGE_KOORDINAT_BOLA_H
