# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from bismillah_fp/target.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class target(genpy.Message):
  _md5sum = "72fecc2344924574cece529ec5202e24"
  _type = "bismillah_fp/target"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 center_bola_x
int64 center_bola_y
int64 target_sudut
int64 kecepatan_x
int64 kecepatan_y
int64 kecepatan_teta"""
  __slots__ = ['center_bola_x','center_bola_y','target_sudut','kecepatan_x','kecepatan_y','kecepatan_teta']
  _slot_types = ['int64','int64','int64','int64','int64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       center_bola_x,center_bola_y,target_sudut,kecepatan_x,kecepatan_y,kecepatan_teta

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(target, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.center_bola_x is None:
        self.center_bola_x = 0
      if self.center_bola_y is None:
        self.center_bola_y = 0
      if self.target_sudut is None:
        self.target_sudut = 0
      if self.kecepatan_x is None:
        self.kecepatan_x = 0
      if self.kecepatan_y is None:
        self.kecepatan_y = 0
      if self.kecepatan_teta is None:
        self.kecepatan_teta = 0
    else:
      self.center_bola_x = 0
      self.center_bola_y = 0
      self.target_sudut = 0
      self.kecepatan_x = 0
      self.kecepatan_y = 0
      self.kecepatan_teta = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6q().pack(_x.center_bola_x, _x.center_bola_y, _x.target_sudut, _x.kecepatan_x, _x.kecepatan_y, _x.kecepatan_teta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.center_bola_x, _x.center_bola_y, _x.target_sudut, _x.kecepatan_x, _x.kecepatan_y, _x.kecepatan_teta,) = _get_struct_6q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6q().pack(_x.center_bola_x, _x.center_bola_y, _x.target_sudut, _x.kecepatan_x, _x.kecepatan_y, _x.kecepatan_teta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.center_bola_x, _x.center_bola_y, _x.target_sudut, _x.kecepatan_x, _x.kecepatan_y, _x.kecepatan_teta,) = _get_struct_6q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6q = None
def _get_struct_6q():
    global _struct_6q
    if _struct_6q is None:
        _struct_6q = struct.Struct("<6q")
    return _struct_6q
